package com.smarterdroid.wififiletransfer;

/* This class is generated by JADX */
/* renamed from: com.smarterdroid.wififiletransfer.R  reason: case insensitive filesystem */
public final class C0000R {

    /* renamed from: com.smarterdroid.wififiletransfer.R$drawable */
    public static final class drawable {
        public static final int gray_gradient1 = 2130837504;
        public static final int gray_gradient2 = 2130837505;
        public static final int ic_email = 2130837506;
        public static final int ic_help = 2130837507;
        public static final int ic_logo = 2130837508;
        public static final int ic_quit = 2130837509;
        public static final int ic_settings = 2130837510;
        public static final int ic_upgrade2 = 2130837511;
        public static final int ic_wft2_h = 2130837512;
        public static final int ic_wft2_h_off = 2130837513;
        public static final int ic_wft2_l = 2130837514;
        public static final int ic_wft2_m = 2130837515;
        public static final int myshape = 2130837516;
        public static final int rounded_corners = 2130837517;
    }

    /* renamed from: com.smarterdroid.wififiletransfer.R$layout */
    public static final class layout {
        public static final int chooser_list = 2130903040;
        public static final int help_main = 2130903041;
        public static final int list_item = 2130903042;
        public static final int main = 2130903043;
        public static final int widgetlayout = 2130903044;
    }

    /* renamed from: com.smarterdroid.wififiletransfer.R$xml */
    public static final class xml {
        public static final int settings = 2130968576;
        public static final int widget_info = 2130968577;
    }

    /* renamed from: com.smarterdroid.wififiletransfer.R$string */
    public static final class string {
        public static final int appname_pro = 2131034112;
        public static final int appname_free = 2131034113;
        public static final int preferences = 2131034114;
        public static final int help = 2131034115;
        public static final int email_developer = 2131034116;
        public static final int upgrade = 2131034117;
        public static final int quit = 2131034118;
        public static final int pressbutton = 2131034119;
        public static final int start = 2131034120;
        public static final int stop = 2131034121;
        public static final int enterurl = 2131034122;
        public static final int offline = 2131034123;
        public static final int emaillink = 2131034124;
        public static final int wft_logo_description = 2131034125;
        public static final int buttonbar_description = 2131034126;
        public static final int or = 2131034127;
        public static final int nowificonnection = 2131034128;
        public static final int pressstart = 2131034129;
        public static final int sendlinkvia = 2131034130;
        public static final int wfturl = 2131034131;
        public static final int visiturl = 2131034132;
        public static final int selectemailapp = 2131034133;
        public static final int youcannowaccess = 2131034134;
        public static final int willruninbackground = 2131034135;
        public static final int freeversionrunning = 2131034136;
        public static final int needstobestopped = 2131034137;
        public static final int whatsnew = 2131034138;
        public static final int wifinotconnected = 2131034139;
        public static final int openwifistettings = 2131034140;
        public static final int memorycardnotreadable = 2131034141;
        public static final int ifyourphoneis = 2131034142;
        public static final int licensecheckfailed = 2131034143;
        public static final int typeyourmessagehere = 2131034144;
        public static final int ok = 2131034145;
        public static final int cancel = 2131034146;
        public static final int retry = 2131034147;
        public static final int yes = 2131034148;
        public static final int no = 2131034149;
        public static final int licenseerror = 2131034150;
        public static final int buyapp = 2131034151;
        public static final int helptopics = 2131034152;
        public static final int connectionproblems = 2131034153;
        public static final int howtousewft = 2131034154;
        public static final int frequentlyaskedquestions = 2131034155;
        public static final int getemailsupport = 2131034156;
        public static final int privacy = 2131034157;
        public static final int thisappusesanalytics = 2131034158;
        public static final int pleaseemailany = 2131034159;
        public static final int id = 2131034160;
        public static final int key = 2131034161;
        public static final int enter = 2131034162;
        public static final int choose = 2131034163;
        public static final int password = 2131034164;
        public static final int accesspassword = 2131034165;
        public static final int accesspwdexpl = 2131034166;
        public static final int misc = 2131034167;
        public static final int redirect = 2131034168;
        public static final int redirectexpl = 2131034169;
        public static final int redirectto = 2131034170;
        public static final int themes = 2131034171;
        public static final int themesexpl = 2131034172;
        public static final int showstartdialog = 2131034173;
        public static final int showstartdialogexpl = 2131034174;
        public static final int displaydirsize = 2131034175;
        public static final int slowerpageloading = 2131034176;
        public static final int restorefiles = 2131034177;
        public static final int restorefilesexpl = 2131034178;
        public static final int restorefilesdialog = 2131034179;
        public static final int startappautomatically = 2131034180;
        public static final int homenetwork = 2131034181;
        public static final int autostartoff = 2131034182;
        public static final int autostart = 2131034183;
        public static final int port = 2131034184;
        public static final int portandrange = 2131034185;
        public static final int sslport = 2131034186;
        public static final int sslportandrange = 2131034187;
        public static final int sslencryption = 2131034188;
        public static final int sslexpl = 2131034189;
        public static final int validvalues = 2131034190;
        public static final int portscannotbeidentical = 2131034191;
        public static final int yourbrowserwillshow = 2131034192;
        public static final int hidden = 2131034193;
        public static final int advancedsettings = 2131034194;
        public static final int networksettings = 2131034195;
        public static final int navlinks = 2131034196;
        public static final int editnavlinks = 2131034197;
        public static final int linklabel = 2131034198;
        public static final int linktarget = 2131034199;
        public static final int socialmediabuttons = 2131034200;
        public static final int disablefacebook = 2131034201;
        public static final int analyticsoptout = 2131034202;
        public static final int disableanonymousreporting = 2131034203;
        public static final int enterpassword = 2131034204;
        public static final int submit = 2131034205;
        public static final int reset = 2131034206;
        public static final int forgotpassword = 2131034207;
        public static final int logout = 2131034208;
        public static final int howtouse = 2131034209;
        public static final int upgradetopro = 2131034210;
        public static final int filebrowser = 2131034211;
        public static final int mediagallery = 2131034212;
        public static final int home = 2131034213;
        public static final int internalstorage = 2131034214;
        public static final int sdcard = 2131034215;
        public static final int usbstorage = 2131034216;
        public static final int myphotos = 2131034217;
        public static final int mypictures = 2131034218;
        public static final int mymusic = 2131034219;
        public static final int myvideos = 2131034220;
        public static final int pictures = 2131034221;
        public static final int music = 2131034222;
        public static final int videos = 2131034223;
        public static final int currentdir = 2131034224;
        public static final int download = 2131034225;
        public static final int delete = 2131034226;
        public static final int move = 2131034227;
        public static final int makezipfile = 2131034228;
        public static final int newdirectory = 2131034229;
        public static final int name = 2131034230;
        public static final int size = 2131034231;
        public static final int lastmodified = 2131034232;
        public static final int actions = 2131034233;
        public static final int parentdir = 2131034234;
        public static final int actiondownload = 2131034235;
        public static final int actiondelete = 2131034236;
        public static final int actionrename = 2131034237;
        public static final int actioncopy = 2131034238;
        public static final int actionzip = 2131034239;
        public static final int actionunzip = 2131034240;
        public static final int actioninstall = 2131034241;
        public static final int total = 2131034242;
        public static final int b = 2131034243;
        public static final int kb = 2131034244;
        public static final int mb = 2131034245;
        public static final int gb = 2131034246;
        public static final int in = 2131034247;
        public static final int files = 2131034248;
        public static final int directories = 2131034249;
        public static final int devicestatus = 2131034250;
        public static final int spaceavailable = 2131034251;
        public static final int batterylevel = 2131034252;
        public static final int wifissid = 2131034253;
        public static final int uploadfiles = 2131034254;
        public static final int tocurrentdirectory = 2131034255;
        public static final int overallprogress = 2131034256;
        public static final int fileprogress = 2131034257;
        public static final int selectfiles = 2131034258;
        public static final int selectdirectory = 2131034259;
        public static final int startupload = 2131034260;
        public static final int overwriteexistingfiles = 2131034261;
        public static final int trybasicuploadform = 2131034262;
        public static final int holdctrl = 2131034263;
        public static final int fileswillbesaved = 2131034264;
        public static final int directorynotwriteable = 2131034265;
        public static final int learnmore = 2131034266;
        public static final int mbperfilemax = 2131034267;
        public static final int touploadfilesofanysize = 2131034268;
        public static final int uploaded = 2131034269;
        public static final int ratethisapp = 2131034270;
        public static final int switchtoflashuploader = 2131034271;
        public static final int ifyoulikeourapp = 2131034272;
        public static final int dontshowthismsgagain = 2131034273;
        public static final int processingpleasewait = 2131034274;
        public static final int hithere = 2131034275;
        public static final int show = 2131034276;
        public static final int allpictures = 2131034277;
        public static final int camerapictures = 2131034278;
        public static final int otherpictures = 2131034279;
        public static final int sortby = 2131034280;
        public static final int datenewestfirst = 2131034281;
        public static final int dateoldestfirst = 2131034282;
        public static final int nameascending = 2131034283;
        public static final int namedescending = 2131034284;
        public static final int sizelargestfirst = 2131034285;
        public static final int sizesmallestfirst = 2131034286;
        public static final int gotoparentdir = 2131034287;
        public static final int pages = 2131034288;
        public static final int js_progressOverall = 2131034289;
        public static final int js_currentTitle = 2131034290;
        public static final int js_currentFile = 2131034291;
        public static final int js_currentProgress = 2131034292;
        public static final int js_fileName = 2131034293;
        public static final int js_remove = 2131034294;
        public static final int js_removeTitle = 2131034295;
        public static final int js_fileError = 2131034296;
        public static final int js_duplicate = 2131034297;
        public static final int js_sizeLimitMin = 2131034298;
        public static final int js_sizeLimitMax = 2131034299;
        public static final int js_fileListMax = 2131034300;
        public static final int js_fileListSizeMax = 2131034301;
        public static final int js_httpStatus = 2131034302;
        public static final int js_securityError = 2131034303;
        public static final int js_ioError = 2131034304;
        public static final int js_delAlltxt = 2131034305;
        public static final int js_confirmDeltxt1 = 2131034306;
        public static final int js_WFT_ok = 2131034307;
        public static final int js_WFT_cancel = 2131034308;
        public static final int js_confirmInstalltxt1 = 2131034309;
        public static final int js_confirmInstalltxt = 2131034310;
        public static final int js_confirmRentxt1 = 2131034311;
        public static final int js_confirmCopytxt1 = 2131034312;
        public static final int js_confirmUnziptxt = 2131034313;
        public static final int js_confirmZiptxt1 = 2131034314;
        public static final int js_makeDirtxt1 = 2131034315;
        public static final int js_noFilesSelectedtxt1 = 2131034316;
        public static final int js_WFT_download = 2131034317;
        public static final int js_WFT_delete = 2131034318;
        public static final int js_WFT_zip = 2131034319;
        public static final int js_WFT_move = 2131034320;
        public static final int js_WFT_install = 2131034321;
        public static final int js_WFT_copy = 2131034322;
        public static final int js_WFT_rename = 2131034323;
        public static final int js_WFT_unzip = 2131034324;
        public static final int js_downAlltxt1 = 2131034325;
        public static final int js_WFT_individual_files = 2131034326;
        public static final int js_WFT_one_zip_archive = 2131034327;
        public static final int js_zipAlltxt1 = 2131034328;
        public static final int js_moveAlltxt1 = 2131034329;
        public static final int js_WFT_MacMSG = 2131034330;
        public static final int js_WFT_FlashMSG = 2131034331;
        public static final int js_WFT_Uploading = 2131034332;
        public static final int js_uploadFailed = 2131034333;
        public static final int js_pl_selectfiles = 2131034334;
        public static final int js_pl_selectfolder = 2131034335;
        public static final int js_pl_addfilestoqueue = 2131034336;
        public static final int js_pl_filename = 2131034337;
        public static final int js_pl_status = 2131034338;
        public static final int js_pl_size = 2131034339;
        public static final int js_pl_addfiles = 2131034340;
        public static final int js_pl_stopcurrentupload = 2131034341;
        public static final int js_pl_startuploadingqueue = 2131034342;
        public static final int js_pl_uploadedfiles = 2131034343;
        public static final int js_pl_na = 2131034344;
        public static final int js_pl_dragfileshere = 2131034345;
        public static final int js_pl_fileextensionerror = 2131034346;
        public static final int js_pl_filesizerror = 2131034347;
        public static final int js_pl_initerror = 2131034348;
        public static final int js_pl_httperror = 2131034349;
        public static final int js_pl_securityerror = 2131034350;
        public static final int js_pl_genericerror = 2131034351;
        public static final int js_pl_ioerror = 2131034352;
        public static final int js_pl_stopupload = 2131034353;
        public static final int js_pl_startupload = 2131034354;
        public static final int js_pl_filesqueued = 2131034355;
        public static final int js_pl_yourbrowserdoesnotsupport = 2131034356;
        public static final int ga_trackingId = 2131034357;
        public static final int appname = 2131034358;
    }

    /* renamed from: com.smarterdroid.wififiletransfer.R$array */
    public static final class array {
        public static final int themeColors = 2131099648;
        public static final int themeNames = 2131099649;
        public static final int themeValues = 2131099650;
    }

    /* renamed from: com.smarterdroid.wififiletransfer.R$style */
    public static final class style {
        public static final int WFTTheme = 2131165184;
    }

    /* renamed from: com.smarterdroid.wififiletransfer.R$bool */
    public static final class bool {
        public static final int ga_autoActivityTracking = 2131230720;
        public static final int ga_reportUncaughtExceptions = 2131230721;
    }

    /* renamed from: com.smarterdroid.wififiletransfer.R$integer */
    public static final class integer {
        public static final int ga_sessionTimeout = 2131296256;
    }

    /* renamed from: com.smarterdroid.wififiletransfer.R$id */
    public static final class id {
        public static final int btnChoose = 2131361792;
        public static final int layout_relative2 = 2131361793;
        public static final int image_logo = 2131361794;
        public static final int textview_topics = 2131361795;
        public static final int scrollview_main = 2131361796;
        public static final int textview_pressstart = 2131361797;
        public static final int button_start = 2131361798;
        public static final int textview_url_label = 2131361799;
        public static final int textview_url = 2131361800;
        public static final int spacer = 2131361801;
        public static final int button_settings = 2131361802;
        public static final int button_help = 2131361803;
        public static final int button_upgrade = 2131361804;
        public static final int wftwidgetlayout = 2131361805;
        public static final int widget_image = 2131361806;
        public static final int urltext = 2131361807;
    }
}
